name: CI/CD Pipeline

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t nodejs-ci-cd .

    - name: Push Docker image to Docker Hub
      run: |
        echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
        docker tag nodejs-ci-cd $DOCKER_HUB_USERNAME/nodejs-ci-cd
        docker push $DOCKER_HUB_USERNAME/nodejs-ci-cd
  
  deploy:
      runs-on: ubuntu-latest

      needs: build

      environment: 
        name: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Docker Login
          run: |
            echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
            docker tag nodejs-ci-cd $DOCKER_HUB_USERNAME/nodejs-ci-cd
            docker push $DOCKER_HUB_USERNAME/nodejs-ci-cd
          
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
          env:
            AZURE_WEBAPP_NAME: nodejs-ci-cd
          with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            images: '$DOCKER_HUB_USERNAME/nodejs-ci-cd:latest'